var keyCode = {
	RC_CHANNEL_UP              : 427,	
	RC_CHANNEL_DOWN            : 428,	
	RC_VOLUME_UP               : 447,
	RC_VOLUME_DOWN             : 448,	
	RC_MUTE                    : 449,	
	RC_PAUSE_ON                : 463,	
	RC_PAUSE_OFF               : 415,		
	RC_POWER_SWITCH            : 409,	
	RC_TELETEXT_RED            : 403,	
	RC_TELETEXT_GREEN          : 404,	
	RC_TELETEXT_YELLOW         : 405,	
	RC_TELETEXT_BLUE           : 406,	
	RC_OK                      : 13,	
	RC_GUIDE                   : 458,	
	RC_LEFT_ARROW              : 37,
	RC_RIGHT_ARROW             : 39,	
	RC_UP_ARROW                : 38,	
	RC_DOWN_ARROW              : 40,	
	RC_UP_ARROW_SMALL          : 33,	
	RC_DOWN_ARROW_SMALL        : 34,	
	RC_MENU                    : 462,	
	RC_BACK                    : 461,	
	RC_DEL                     : 3,
	RC_PVR                     : 256,	
	RC_STOP_PLAY               : 413,	
	RC_FAST_FORWARD            : 417,	
	RC_FAST_BACKWARD           : 412,	
	RC_PLAY_FIRST              : 424,
	RC_PLAY_END                : 425,
	
	RC_0 : 48,
	RC_1 : 49,
	RC_2 : 50,
	RC_3 : 51,
	RC_4 : 52,
	RC_5 : 53,
	RC_6 : 54,
	RC_7 : 55,
	RC_8 : 56,
	RC_9 : 57
	
};